times = ('Palmeiras' , 'Atlético - MG' , 'Fortaleza' , 'Bragantino', 'Athletico - PR', 'Flamengo','Ceará', 'Atlético - GO', 'Bahia', 'Fluminense', 'Santos', 'Corinthians', 'Internacional', 'Juventude', 'Cuiabá', 'Sport', 'São Paulo', 'América - MG', 'Grêmio', 'Chapecoense')
print(f'Lista de times do Brasileirão = {times}')
print('='*300)
print(f'Os primeiros colocados são = {times[0:5]}')
print('='*300)
print(f'Os quatro últimos são = {times[-4:]}')
print('='*300)
print(f'Em ordem Alfabética = {sorted(times)}')
print('='*300)
print(f'A Chapecoense está em {times.index("Chapecoense")+1}° posição')